apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-user
spec:
  selector:
    app: {{ .Release.Name }}-user
  ports:
    - port: {{ .Values.user.port }}
      targetPort: {{ .Values.user.port }}

