replicaCount: 3

image:
  tag: ""

postgres:
  storage: 1Gi

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

config:
  appName: "Production App"

ingress:
  host: myapp.com

