replicaCount: 3

image:
  tag: "c815010d288095c6e5aa4e2e3d0dd73c5624982f"

postgres:
  storage: 1Gi

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

config:
  appName: "Production App"

ingress:
  host: myapp.com

