replicaCount: 1

image:
  tag: "8bf63362682ef22cc7ec318c95e6b1d3d678312e"

user:
  image: diwakar5041/user-service
  port: 3001

product:
  image: diwakar5041/product-service
  port: 3001

order: 
  image: diwakar5041/order-service
  port: 3001

gateway:
  image: diwakar5041/app-gateway
  port: 3001

postgres:
  user: admin
  password: password
  database: mydb
  storage: 300Mi

ingress:
  host: myapp.local

