apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-user
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-user
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-user
    spec:
      containers:
        - name: user
          image: {{ .Values.user.image }}:{{ .Values.user.tag }}
          ports:
            - containerPort: {{ .Values.user.port }}

          env:
            - name: APP_NAME
              valueFrom: 
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: APP_NAME

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: SECRET_KEY

            - name: DB_HOST
              value: "{{ .Release.Name }}-postgres"
              
          resources:
            requests:
              cpu: {{ .Values.resources.resources.cpu }}
              memory: {{ .Values.resources.resources.memory }}
            
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          
          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.user.port }}
            failureThreshold: 50
            periodSeconds: 6

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.user.port }}
            initialDelaySeconds: 0
            periodSeconds: 10

          readinessProbe: 
            httpGet:
              path: /ready
              port: {{ .Values.user.port }}
            initialDelaySeconds: 0
            periodSeconds: 5




