replicaCount: 3

postgres:
  storage: 1Gi

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

config:
  appName: "Production Application"

secret:
  secretKey: "mysecret"
