replicaCount: 3
user:
  tag: c6c8bba91c6358d4f24f4ccdfa080fa9dd1e8c1a
product:
  tag: c6c8bba91c6358d4f24f4ccdfa080fa9dd1e8c1a
gateway:
  tag: c6c8bba91c6358d4f24f4ccdfa080fa9dd1e8c1a
postgres:
  storage: 1Gi
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
config:
  appName: "Production App"
ingress:
  host: myapp.com
