replicaCount: 3

user:
  tag: latest

product:
  tag: latest

gateway:
  tag: latest

postgres:
  storage: 1Gi

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

config:
  appName: "Production App"

ingress:
  host: myapp.com

